global:
  log_level: INFO
  log_file: deathconfuser.log
  default_preset: null

recon:
  wordlist: wordlists/common.txt
  threads: 10
  timeout: 30
  user_agents:
    - Mozilla/5.0
  mode: stealth
  v2_engine: false

exploit:
  package_managers: [npm, pip]
  auto_publish: false
  verify_callback: true
  retries: 3
  timeout: 30

payloads:
  polymorphic: false
  builder: template
  stealth_sleep: 0
  obfuscation:
    base64: false
    xor: false
    timing: false

opsec:
  proxy_rotation: false
  proxy_list: []
  use_proxy: false
  proxy_chain: []
  use_tor: false
  doh_resolver: ""
  sandbox_detect: false
  scrub_logs: false
  burner_profiles: false
  jitter: false
  stealth_delay: ""
  rotate_metadata: false
  burner_accounts: false
  random_user_agent: false
  random_versions: false
  publish_jitter: ""

report:
  formats: [json]
  output_dir: reports
  template_dir: templates
  callback_log: false

callback:
  http_url: ""
  dns_domain: ""
  interactsh:
    enabled: false
    server: ""
  burp:
    enabled: false
    collaborator_url: ""

concurrency:
  limit: 10
  retries: 1
  timeout: 30

